apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: k8s-auth-injector
webhooks:
- name: k8s-auth-injector.alvaroaleman.io
  failurePolicy: Ignore
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  clientConfig:
    service:
      namespace: kube-system
      name: k8s-auth-injector
    caBundle: <<CACERT>>
